### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hzoo** [babel/phabricator-to-github#2]
> CONTRIBUTING: https://github.com/babel/phabricator-to-github/blob/master/CONTRIBUTING.md

Just an issue to track what we can/should do to migrate
### Info

Old issue id range: `1 - 3086` (maniphest_task)
New issue range: `> 6637`
Number of new issues: `~871`
Number of new comments: `~2940`
Github ratelimit is 5000 requests/hour (https://developer.github.com/v3/#rate-limiting)

---
### Open questions:
- [x] ~~How to compare/merge issues? Someone needs to check if the github id is somewhere in the phabricator dump. Otherwise we need to retrieve all comments beforehand.~~ Phabricator ids match the github ids.
- [x] What was the last phabricatorID for the import from github? IF we know that we can easily know which to merge and which to create (3086)
- [x] ~~Do we want to migrate issues that do not exist yet in github but are already closed?~~ YES
- [x] Do we need to migrate attachments? (There are 41 attachments that can be migrated by hand)
- [x] The issue import API is async, which means that issues could get imported in random order. We could wait till the import of one issue is finished and then send the next, but then the import might take several hours (I've seen delays of up to a minute between sending request and issue being imported.)

---
### Tasks:
- [x] phabricator db dump -> more consumable format #1 
- [x] script to [create a new github issue](https://developer.github.com/v3/issues/#create-an-issue) with the [issues api](https://developer.github.com/v3/issues/)
- [x] script to create all the comments for this new issues.
- [x] script to [merge existing issues that had more comments, changes, ...](https://developer.github.com/v3/issues/#edit-an-issue)
- [x] script to close finished issues
- [x] ~~handle the edge case that someone really posts an issue during migration and log these issue numbers (should be easy by just looking if the returned issue number from the api is +1 the last issue number), otherwise they might get lost in the flood of issues.~~
- [x] create a new dummy user that will actually "report" all the migrated stuff in github (maybe `babel-bot`)
- [x] setup a simple issue/pr template in the babel repo https://github.com/babel/babel/pull/3690
- [x] Move parser issues to babylon. (16 Issues,  https://phabricator.babeljs.io/maniphest/query/5cfBx2lNVIJt/#R)

---
- [x] We don't want to spam watchers on github with notifications.
  - Maybe notify all watchers of babel at what time we will do the migration, so they could unwatch the project for that period. 
  - Or maybe we can globally disable notifications?
  - Or contact github about that? Maybe also useful for the api rate limiting
- [x] make sure usernames transfer over correctly
  -  some people don't sign up with github (can we link everything?)
  - is it possible to transfer subscribers?

**Comment by danez** [comment]
I updated the comment a little bit and added more stuff.

In general I think it would be good to "calculate" all the necessary changes to be made to github in the first task, and then as quickly as possible (github api probably has throttling) execute the changes.

**Comment by rmacklin** [comment]
> handle the edge case that someone really posts an issue during migration and log these issue numbers (should be easy by just looking if the returned issue number from the api is +1 the last issue number), otherwise they might get lost in the flood of issues.

Just wanted to mention that it's probably not worth logging these issues yourself because that data can be queried easily from the issues search. You could find them by searching with a query that uses a range filter on the created timestamp (using the start and end timestamps of the migration script) and excludes all issues filed by the bot user. For example:

```
is:issue created:2016-07-26T22:59:10-07:00..2016-07-26T23:04:10-07:00 -author:babel-bot
```

**Comment by danez** [comment]
Thanks, that is even easier.

**Comment by hzoo** [comment]
Ok I contacted github - we should try using the (unfinished) API described in https://gist.github.com/jonmagic/5282384165e0f86ef105 to get around some of the issues we mentioned above

**Comment by hzoo** [comment]
for attachments we can link to the issue instead? I wonder how many of those there are anyway

we can move the parser issues manually too
